Repository micronaut-projects/micronaut-problem-json, pull requests merged in 2022-09, with the labels that each got.

#192 build: bump up serde to 1.3.1
  gradle.properties
Labels: type: dependency-upgrade

#188 build: Bump Micronaut to 3.6.0
  gradle.properties
Labels: relates-to: build

#194 fix: serde serialization of Constraint Violation Exception
  problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
  problem-json/src/main/java/io/micronaut/problem/violations/ConstraintViolationThrowableProblem.java
  problem-json/src/main/java/io/micronaut/problem/violations/Violation.java
  test-suite-serde-java/src/test/java/io/micronaut/problem/ProblemConstraintsTest.java
Labels: type: bug

#200 Use serde version from Micronaut BOM
  gradle.properties
  test-suite-serde-java/build.gradle
Labels: relates-to: build
