Repository micronaut-projects/micronaut-problem-json, pull requests merged in 2022-01, with the labels that each got.

#87 Upgrade to Gradle 7.3.3, upgrade actions and use official GraalVM GitHub Action
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#88 docs: linkfix datatracker.ietf.org
  src/main/docs/guide/introduction.adoc
Labels: type: docs

#96 git: don't git ignore build-logic/src/main/java/io/micronaut/build
  .gitignore
Labels: relates-to: build

#98 build: bump up problem to 0.27.1 from 0.26
  gradle.properties
Labels: type: dependency-upgrade

#100 build: bump up serde to 1.0.0-M5
  gradle.properties
Labels: type: dependency-upgrade

#104 build: add bom module
  problem-json-bom/build.gradle
  settings.gradle
Labels: relates-to: build

#105 ci: bump up project version to 2.2.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#106 build: bump up micronaut to 3.3.0-M1
  gradle.properties
Labels: relates-to: build

#107 ci: GraalVM github action from 21.3.0 to 22.0.0.2
  .github/workflows/graalvm.yml
  MAINTAINING.md
Labels: relates-to: build
