Repository micronaut-projects/micronaut-problem-json, pull requests merged in 2023-07, with the labels that each got.

#271 [problem-json] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#277 [problem-json] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#286 Problem-JSON no milestones
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#293 bug: serialization agnostic
  problem-json/build.gradle.kts
  test-suite-groovy/build.gradle
Labels: type: bug

#294 remove unnecessary json.additional-types
  problem-json/build.gradle.kts
  problem-json/src/test/resources/application.yml
  src/main/docs/guide/installation/codec.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/resources/application.yml
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/resources/application.yml
  test-suite-serde-java/build.gradle
  test-suite-serde-java/src/test/resources/application.yml
  test-suite/build.gradle
  test-suite/src/test/resources/application.yml
Labels: type: docs

#298 [problem-json] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
